[project]
name = "metricskit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jan Borowski", email = "bor.jan.g.2018@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
metricskit = "metricskit:main"

[build-system]
requires = ["uv_build>=0.11.14,<0.12.0"]
build-backend = "uv_build"
